name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build
        run: mvn -B -Dskip.ut=true -DskipITs package

  unit-tests:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run unit tests
        run: mvn -B test
      - name: Archive unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports/**
            target/test-classes/**

  integration-tests:
    name: Integration Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run integration tests
        run: mvn -B -Dskip.ut=true verify
      - name: Archive integration test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports
          path: |
            target/failsafe-reports/**
            target/maven-it/**
            target/itf-repo/**

  test-report:
    name: Test Report
    needs: [ unit-tests, integration-tests ]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download unit test reports
        uses: actions/download-artifact@v4
        with:
          name: surefire-reports
      - name: Download integration test reports
        uses: actions/download-artifact@v4
        with:
          name: failsafe-reports
      - name: List downloaded reports #debug
        if: always()
        run: |
          echo "UNIT:"
          ls -Rlah surefire-reports || true
          echo "IT:"
          ls -Rlah failsafe-reports || true
      - uses: dorny/test-reporter@v2.1.1
        with:
          name: Unit and Integration Tests
          path: |
            surefire-reports/surefire-reports/*.xml
            failsafe-reports/failsafe-reports/TEST-*.xml
          reporter: java-junit