name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2.1.1
        with:
        with:
          artifact: test-results
          name: Unit and Integration Tests
          path: |
            target/surefire-reports/*.xml
            target/failsafe-reports/TEST-*.xml
          reporter: java-junit